#!/bin/sh
#############################################################################
##
#W  make_doc          make Example Package documentation          Greg Gamble
##
## Slightly modified by Leonard Soicher for use with GRAPE.
## 
#H  $Id: make_doc,v 4.1 2001/10/07 02:37:40 gap Exp $
##
##  This shell script uses TeX, BibTeX and MakeIndex to build the .dvi, Adobe
##  PDF, PostScript (commented out) and  HTML  (provided  you  have  tth  and
##  etc/convert.pl) documentation for the Example Package.
##

echo "TeXing documentation"
# TeX the manual
tex manual
bibtex manual
# TeX the manual again to incorporate the ToC ... and build the index
tex manual; ./manualindex manual
# Finally TeX the manual again to get cross-references right
tex manual
# Create PDF version
pdftex manual; pdftex manual 

# The HTML version of the manual
mkdir -p ../htm
echo "Creating HTML documentation"
./convert.pl -t -c -n matgrp . ../htm

#############################################################################
##
#E
